### ISSUE TITLE
vocab path

### ISSUE THREAD

**Issue by nhathoang0110** [huynhnhathao/vietnamese_spelling_error_correction#1]
Chào a. Em có sử dụng file createData của a thì bị lỗi ở phần liên quan đến vocab_path. Không biết là file random_vocab tạo từ đâu ạ ? Em cảm ơn ạ

**Comment by huynhnhathao** [comment]
random_vocab là file chứa các từ random để khi em gọi hàm `replace_with_random_word(self,text, onehot_label):` nó sẽ chọn ra một từ random trong `text` để thay vào một từ random trong random_vocab, anh quên chưa chia sẻ file vocab path, em tải về sửa lại đường dẫn là xài được
link đên vocab_path: https://drive.google.com/file/d/1VjHED1hE6i4Is-pLafQxkDXxFPsE5WyE/view?usp=sharing

**Comment by nhathoang0110** [comment]
a cho em hỏi thêm ở chỗ tạo dữ liệu, theo như code trên colab của a thì a chỉ mới tạo mỗi mode là random word phải ko ạ ? Vì em thấy trong code a không sử dụng các mode khác ?

**Comment by huynhnhathao** [comment]
anh dùng nhiều mode chứ em, tại anh xóa rồi đó. Anh khuyên em tạo lại data để huấn luyện, nói chung là làm lại mọi bước mà anh đã làm để lấy được nhiều kiến thức nhất. Còn code anh chia sẻ chỉ nên tham khảo như cái sườn, và nên đọc từng dòng để xem nó làm gì chứ không nên chỉ chạy hàm và lấy output. Em cứ sửa lại nếu em cho là hàm của em viết hay hơn.

**Comment by nhathoang0110** [comment]
a cho e hỏi thêm là phần trainning model, chỗ đọc train data ở cuối a có đọc train1 và train2, e chưa rõ tại sao lại có 2 folder như vậy, lúc create data mình chỉ có 1 cái train data và lưu vào đúng k ạ ?

**Comment by huynhnhathao** [comment]
Vì lúc đầu data lớn anh chia ra nhiều file để xử lý cho dễ, load 2 file data lên xong nối lại

 `train_data = torch.utils.data.ConcatDataset([train1, train2])`

Anh chia sẻ cho em thư mục chứa toàn bộ data, em mở thư mục theo đường dẫn như trong code sẽ hiểu chỗ nào cần data như thế nào

https://drive.google.com/drive/folders/1En5uILZJUJrwa-BcFdwEWSWz60xrDeGY?usp=sharing
