### ISSUE TITLE
phương pháp

### ISSUE THREAD

**Issue by nhathoang0110** [huynhnhathao/vietnamese_spelling_error_correction#2]
Em chào a. Sau khi đọc kĩ phần lí thuyế của a, thì e nhận thấy mô hình này có vẻ có 1 điểm yếu là nó sẽ dự đoán vị trí sai chính tả, điều naỳ mô hình detector có thể hoạt động tốt (97%) tuy nhiên việc sửa lại từ đó dựa vào mô hình corrector thì nó dựa vào ngữ cảnh. điều đó có thể sẽ sai sót nhiều. Không biết em nghĩ thế có đúng k ạ ?

**Comment by huynhnhathao** [comment]
đúng rồi em, corrector nó có thể đề xuất bất cứ từ nào mà nó cho là hợp lý, hay là nó đã nhìn thấy trong tập train của nó, mà từ đó  có thể ko là từ mà em muốn. Tuy nhiên ko thể trách nó được, mà điều mình có thể làm là bảo nó đề xuất ra nhiều từ mà nó cho là có lý, xong đo khoảng cách từ đề xuất của nó đến từ bị sai chính tả và chọn từ gần nhất, khoảng cách có thể là edit distance chẳng hạn, mà làm như vậy thì em cần viết nhiều code hơn, với lại cái corrector nó chỉ đề xuất có một từ thôi em phải tìm cách đề nó đề xuất ra nhiều từ nữa,...

**Comment by nhathoang0110** [comment]
Vâng ạ. Việc đề xuất từ mới ở đây là mô hình pretrained, vậy thì nó hoàn toàn là phụ thuộc mô hình đó, còn việc mình train chỉ là giúp cho mô hinh detector phải k ạ ? 
Và anh đã thử nghiệm việc thêm nhiều đề xuất vào chưa ạ ? Em cảm ơn

**Comment by huynhnhathao** [comment]
đúng rồi em, anh vẫn chưa thử nghiệm việc cho nó đề xuất nhiều từ, anh cũng ko biết là việc đó có làm được hay ko, em có thể tìm hiểu xem làm được ko rồi nâng cấp mô hình lên, 

anh nghĩ là tìm hiểu sâu trong phần mô hình pretrained của transformer để xem có mod được trong kiến trúc nó, vì lúc đề xuất một từ mô hình sẽ predict một vector xác suất có độ dài bằng số từ vựng, xong sẽ chọn ra từ có xác suất cao nhất để đề xuất. nếu em tìm ra được vector lúc nó predict thì em có thể chọn n từ có xác xuất cao nhất ra, sao đó làm như anh nói ở trên. Mà chắc chắn là sẽ không dễ vì từ vựng mà nó dùng là subword, nên có thể ko dễ như anh nói
