### ISSUE TITLE
tách từ

### ISSUE THREAD

**Issue by nhathoang0110** [huynhnhathao/vietnamese_spelling_error_correction#3]
Em chào a. Em muốn hỏi thêm về phần tách từ anh sử dụng. Em có tìm hiểu về nó tuy nhiên vẫn chưa hiểu rõ lắm, em thấy nó có vẻ tách thành tiếng, và có khi là đến mức chữ cái. Vậy a cho e hỏi lúc nó trainning phần tách từ từ 1 văn bản raw thì nó làm gì trong quá trình trainning đó ạ ? Và tại sao lúc tách từ thì lại mỗi lần chạy lại cho một kết quả khác nhau

**Comment by huynhnhathao** [comment]
phần tách từ dùng sentence piece tokenizer em có thể tìm hiểu kĩ trong bài viết này nha
https://towardsdatascience.com/sentencepiece-tokenizer-demystified-d0a3aac19b15
