### ISSUE TITLE
phương pháp

### ISSUE THREAD

**Issue by nhathoang0110** [huynhnhathao/vietnamese_spelling_error_correction#4]
em chào a. a cho e hỏi là lúc a tạo dữ liệu huấn luyện, thì mình dùng tokenizer của nltk và lưu vị trí từ sai. tuy nhiên khi đưa vào mô hình detector thì là tokenizer theo sentencepiece tokenizer , như vậy thì nếu vị trí đó bị tách ra khác thì tất cả các token ở đó đều sai phải k ạ ?

**Comment by huynhnhathao** [comment]
chào em, đúng rồi em, ví dụ từ "khuyea" là sai chính tả và có nhãn là 1, sau khi dùng sentencepiece tokenizer nó có thể bị tách thành "kh, uy, ea" tạo ra 3 token, thì cả 3 token này phải được gán nhãn là '"1 1 1" vì nó thuộc một từ sai
